// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2iTE_Ow3XpYZzKCyvbPj-7qSWuY3m13c',
    appId: '1:264105353293:web:7a7e5cc0282dbc8f963c04',
    messagingSenderId: '264105353293',
    projectId: 'aquascape-mobile',
    authDomain: 'aquascape-mobile.firebaseapp.com',
    storageBucket: 'aquascape-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBmGpTuOSBFp8EMMYnGQMYgV8m37mt25E',
    appId: '1:264105353293:android:b4b323c9965cf6cc963c04',
    messagingSenderId: '264105353293',
    projectId: 'aquascape-mobile',
    storageBucket: 'aquascape-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2c0nnKEfu7_oRfg2RG6QeQyY2uC4QpQ',
    appId: '1:264105353293:ios:f8c30336a5fefd73963c04',
    messagingSenderId: '264105353293',
    projectId: 'aquascape-mobile',
    storageBucket: 'aquascape-mobile.appspot.com',
    iosClientId: '264105353293-lg8qa2ef176rtt2vg1ouistg637q9u76.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquascapeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU2c0nnKEfu7_oRfg2RG6QeQyY2uC4QpQ',
    appId: '1:264105353293:ios:f8c30336a5fefd73963c04',
    messagingSenderId: '264105353293',
    projectId: 'aquascape-mobile',
    storageBucket: 'aquascape-mobile.appspot.com',
    iosClientId: '264105353293-lg8qa2ef176rtt2vg1ouistg637q9u76.apps.googleusercontent.com',
    iosBundleId: 'com.example.aquascapeMobile',
  );
}
